version: '3.8'

services:
  mihajlovautorepairapi:
    image: mihajlovautorepairapi
    build:
      context: ./MihajlovAutoRepairApi
      dockerfile: MihajlovAutoRepairApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_NAME=${DB_NAME}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_KEY=${JWT_KEY}
      - JWT_EXPIRYINMINUTES=${JWT_EXPIRYINMINUTES}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  react-app:
    build:
      context: ./mihajlov-auto-repair-frontend
      dockerfile: ./Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    ports:
      - "3000:80"
    depends_on:
      - mihajlovautorepairapi
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
